AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/DotPosition:
  EnforcedStyle: trailing

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'lib/battleship/screen.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/battleship/screen.rb'
