AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/DotPosition:
  EnforcedStyle: trailing

Lint/HandleExceptions:
  Exclude:
    - 'exe/battleship'

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'lib/battleship/screen.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/battleship/screen.rb'
    - 'lib/battleship/grid.rb'
    - 'lib/battleship/game.rb'

Metrics/AbcSize:
  Exclude:
    - 'lib/battleship/screen.rb'
    - 'lib/battleship/game.rb'
